"""SIC → GICS sector crosswalk, for point-in-time sector classification.

Fixes an undisclosed lookahead in the Wikipedia-based sector acquisition
(``acquisition/universe.py``): that path scrapes a single *present-day*
GICS classification and applies it retroactively to the entire backtest,
even though GICS sector membership genuinely changes over time (e.g. the
2018 restructuring that created the Communication Services sector). This
module instead derives sector from each filing's own point-in-time SEC
SIC code (genuinely dated to that filing -- verified against real data:
Agilent's 2009-filing SIC (3825) already differs from its current SEC SIC
(3826)), via a SIC→GICS crosswalk.

**Provenance, read before trusting this for anything beyond directional
sector grouping**: GICS is a proprietary MSCI/S&P classification system;
no free, licensed, authoritative SIC→GICS crosswalk exists. ``SIC_TO_GICS_SECTOR``
below is this project's own judgment mapping, built by classifying each
of SEC's own official SIC code descriptions (``SEC_SIC_CODES``, fetched
verbatim from
https://www.sec.gov/search-filings/standard-industrial-classification-sic-code-list,
retrieved 2026-07-29) against GICS's published 11-sector definitions --
it is not sourced from a licensed GICS crosswalk and should not be cited
as one. Codes whose industry is too generic, defunct, or securities-type
(rather than operating-industry) to confidently place in one of the 11
sectors -- shell/blank-check companies, ADRs, foreign governments,
membership organizations, non-operating establishments, and a handful of
generic services/holding-company catch-alls -- map to ``"Unknown"``
rather than a guessed sector, consistent with this project's rule against
substituting a fabricated value for a genuine unknown.

This crosswalk needs revisiting only if GICS itself restructures its
11 top-level sectors (last happened 2018, then 2023) or if SEC retires/
adds SIC codes (rare) -- it is not expected to need per-run maintenance.
"""

from __future__ import annotations

from typing import Mapping

SEC_SIC_CODES: tuple[tuple[int, str], ...] = (
    (100, "AGRICULTURAL PRODUCTION-CROPS"),
    (200, "AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES"),
    (700, "AGRICULTURAL SERVICES"),
    (800, "FORESTRY"),
    (900, "FISHING, HUNTING AND TRAPPING"),
    (1000, "METAL MINING"),
    (1040, "GOLD AND SILVER ORES"),
    (1090, "MISCELLANEOUS METAL ORES"),
    (1220, "BITUMINOUS COAL & LIGNITE MINING"),
    (1221, "BITUMINOUS COAL & LIGNITE SURFACE MINING"),
    (1311, "CRUDE PETROLEUM & NATURAL GAS"),
    (1381, "DRILLING OIL & GAS WELLS"),
    (1382, "OIL & GAS FIELD EXPLORATION SERVICES"),
    (1389, "OIL & GAS FIELD SERVICES, NEC"),
    (1400, "MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)"),
    (1520, "GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS"),
    (1531, "OPERATIVE BUILDERS"),
    (1540, "GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS"),
    (1600, "HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS"),
    (1623, "WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION"),
    (1700, "CONSTRUCTION - SPECIAL TRADE CONTRACTORS"),
    (1731, "ELECTRICAL WORK"),
    (2000, "FOOD AND KINDRED PRODUCTS"),
    (2011, "MEAT PACKING PLANTS"),
    (2013, "SAUSAGES & OTHER PREPARED MEAT PRODUCTS"),
    (2015, "POULTRY SLAUGHTERING AND PROCESSING"),
    (2020, "DAIRY PRODUCTS"),
    (2024, "ICE CREAM & FROZEN DESSERTS"),
    (2030, "CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES"),
    (2033, "CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES"),
    (2040, "GRAIN MILL PRODUCTS"),
    (2050, "BAKERY PRODUCTS"),
    (2052, "COOKIES & CRACKERS"),
    (2060, "SUGAR & CONFECTIONERY PRODUCTS"),
    (2070, "FATS & OILS"),
    (2080, "BEVERAGES"),
    (2082, "MALT BEVERAGES"),
    (2086, "BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS"),
    (2090, "MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS"),
    (2092, "PREPARED FRESH OR FROZEN FISH & SEAFOODS"),
    (2100, "TOBACCO PRODUCTS"),
    (2111, "CIGARETTES"),
    (2200, "TEXTILE MILL PRODUCTS"),
    (2211, "BROADWOVEN FABRIC MILLS, COTTON"),
    (2221, "BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK"),
    (2250, "KNITTING MILLS"),
    (2253, "KNIT OUTERWEAR MILLS"),
    (2273, "CARPETS & RUGS"),
    (2300, "APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL"),
    (2320, "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS"),
    (2330, "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR"),
    (2340, "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS"),
    (2390, "MISCELLANEOUS FABRICATED TEXTILE PRODUCTS"),
    (2400, "LUMBER & WOOD PRODUCTS (NO FURNITURE)"),
    (2421, "SAWMILLS & PLANTING MILLS, GENERAL"),
    (2430, "MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS"),
    (2451, "MOBILE HOMES"),
    (2452, "PREFABRICATED WOOD BLDGS & COMPONENTS"),
    (2510, "HOUSEHOLD FURNITURE"),
    (2511, "WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)"),
    (2520, "OFFICE FURNITURE"),
    (2522, "OFFICE FURNITURE (NO WOOD)"),
    (2531, "PUBLIC BLDG & RELATED FURNITURE"),
    (2540, "PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES"),
    (2590, "MISCELLANEOUS FURNITURE & FIXTURES"),
    (2600, "PAPERS & ALLIED PRODUCTS"),
    (2611, "PULP MILLS"),
    (2621, "PAPER MILLS"),
    (2631, "PAPERBOARD MILLS"),
    (2650, "PAPERBOARD CONTAINERS & BOXES"),
    (2670, "CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)"),
    (2673, "PLASTICS, FOIL & COATED PAPER BAGS"),
    (2711, "NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING"),
    (2721, "PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING"),
    (2731, "BOOKS: PUBLISHING OR PUBLISHING & PRINTING"),
    (2732, "BOOK PRINTING"),
    (2741, "MISCELLANEOUS PUBLISHING"),
    (2750, "COMMERCIAL PRINTING"),
    (2761, "MANIFOLD BUSINESS FORMS"),
    (2771, "GREETING CARDS"),
    (2780, "BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK"),
    (2790, "SERVICE INDUSTRIES FOR THE PRINTING TRADE"),
    (2800, "CHEMICALS & ALLIED PRODUCTS"),
    (2810, "INDUSTRIAL INORGANIC CHEMICALS"),
    (2820, "PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)"),
    (2821, "PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS"),
    (2833, "MEDICINAL CHEMICALS & BOTANICAL PRODUCTS"),
    (2834, "PHARMACEUTICAL PREPARATIONS"),
    (2835, "IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES"),
    (2836, "BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)"),
    (2840, "SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS"),
    (2842, "SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS"),
    (2844, "PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS"),
    (2851, "PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS"),
    (2860, "INDUSTRIAL ORGANIC CHEMICALS"),
    (2870, "AGRICULTURAL CHEMICALS"),
    (2890, "MISCELLANEOUS CHEMICAL PRODUCTS"),
    (2891, "ADHESIVES & SEALANTS"),
    (2911, "PETROLEUM REFINING"),
    (2950, "ASPHALT PAVING & ROOFING MATERIALS"),
    (2990, "MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL"),
    (3011, "TIRES & INNER TUBES"),
    (3021, "RUBBER & PLASTICS FOOTWEAR"),
    (3050, "GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE"),
    (3060, "FABRICATED RUBBER PRODUCTS, NEC"),
    (3080, "MISCELLANEOUS PLASTICS PRODUCTS"),
    (3081, "UNSUPPORTED PLASTICS FILM & SHEET"),
    (3086, "PLASTICS FOAM PRODUCTS"),
    (3089, "PLASTICS PRODUCTS, NEC"),
    (3100, "LEATHER & LEATHER PRODUCTS"),
    (3140, "FOOTWEAR, (NO RUBBER)"),
    (3211, "FLAT GLASS"),
    (3220, "GLASS & GLASSWARE, PRESSED OR BLOWN"),
    (3221, "GLASS CONTAINERS"),
    (3231, "GLASS PRODUCTS, MADE OF PURCHASED GLASS"),
    (3241, "CEMENT, HYDRAULIC"),
    (3250, "STRUCTURAL CLAY PRODUCTS"),
    (3260, "POTTERY & RELATED PRODUCTS"),
    (3270, "CONCRETE, GYPSUM & PLASTER PRODUCTS"),
    (3272, "CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK"),
    (3281, "CUT STONE & STONE PRODUCTS"),
    (3290, "ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS"),
    (3310, "STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS"),
    (3312, "STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)"),
    (3317, "STEEL PIPE & TUBES"),
    (3320, "IRON & STEEL FOUNDRIES"),
    (3330, "PRIMARY SMELTING & REFINING OF NONFERROUS METALS"),
    (3334, "PRIMARY PRODUCTION OF ALUMINUM"),
    (3341, "SECONDARY SMELTING & REFINING OF NONFERROUS METALS"),
    (3350, "ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS"),
    (3357, "DRAWING & INSULATING OF NONFERROUS WIRE"),
    (3360, "NONFERROUS FOUNDRIES (CASTINGS)"),
    (3390, "MISCELLANEOUS PRIMARY METAL PRODUCTS"),
    (3411, "METAL CANS"),
    (3412, "METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS"),
    (3420, "CUTLERY, HANDTOOLS & GENERAL HARDWARE"),
    (3430, "HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES"),
    (3433, "HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES"),
    (3440, "FABRICATED STRUCTURAL METAL PRODUCTS"),
    (3442, "METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM"),
    (3443, "FABRICATED PLATE WORK (BOILER SHOPS)"),
    (3444, "SHEET METAL WORK"),
    (3448, "PREFABRICATED METAL BUILDINGS & COMPONENTS"),
    (3451, "SCREW MACHINE PRODUCTS"),
    (3452, "BOLTS, NUTS, SCREWS, RIVETS & WASHERS"),
    (3460, "METAL FORGINGS & STAMPINGS"),
    (3470, "COATING, ENGRAVING & ALLIED SERVICES"),
    (3480, "ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)"),
    (3490, "MISCELLANEOUS FABRICATED METAL PRODUCTS"),
    (3510, "ENGINES & TURBINES"),
    (3523, "FARM MACHINERY & EQUIPMENT"),
    (3524, "LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP"),
    (3530, "CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP"),
    (3531, "CONSTRUCTION MACHINERY & EQUIP"),
    (3532, "MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)"),
    (3533, "OIL & GAS FIELD MACHINERY & EQUIPMENT"),
    (3537, "INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS"),
    (3540, "METALWORKG MACHINERY & EQUIPMENT"),
    (3541, "MACHINE TOOLS, METAL CUTTING TYPES"),
    (3550, "SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)"),
    (3555, "PRINTING TRADES MACHINERY & EQUIPMENT"),
    (3559, "SPECIAL INDUSTRY MACHINERY, NEC"),
    (3560, "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT"),
    (3561, "PUMPS & PUMPING EQUIPMENT"),
    (3562, "BALL & ROLLER BEARINGS"),
    (3564, "INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP"),
    (3567, "INDUSTRIAL PROCESS FURNACES & OVENS"),
    (3569, "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC"),
    (3570, "COMPUTER & OFFICE EQUIPMENT"),
    (3571, "ELECTRONIC COMPUTERS"),
    (3572, "COMPUTER STORAGE DEVICES"),
    (3575, "COMPUTER TERMINALS"),
    (3576, "COMPUTER COMMUNICATIONS EQUIPMENT"),
    (3577, "COMPUTER PERIPHERAL EQUIPMENT, NEC"),
    (3578, "CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)"),
    (3579, "OFFICE MACHINES, NEC"),
    (3580, "REFRIGERATION & SERVICE INDUSTRY MACHINERY"),
    (3585, "AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP"),
    (3590, "MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT"),
    (3600, "ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)"),
    (3612, "POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS"),
    (3613, "SWITCHGEAR & SWITCHBOARD APPARATUS"),
    (3620, "ELECTRICAL INDUSTRIAL APPARATUS"),
    (3621, "MOTORS & GENERATORS"),
    (3630, "HOUSEHOLD APPLIANCES"),
    (3634, "ELECTRIC HOUSEWARES & FANS"),
    (3640, "ELECTRIC LIGHTING & WIRING EQUIPMENT"),
    (3651, "HOUSEHOLD AUDIO & VIDEO EQUIPMENT"),
    (3652, "PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS"),
    (3661, "TELEPHONE & TELEGRAPH APPARATUS"),
    (3663, "RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT"),
    (3669, "COMMUNICATIONS EQUIPMENT, NEC"),
    (3670, "ELECTRONIC COMPONENTS & ACCESSORIES"),
    (3672, "PRINTED CIRCUIT BOARDS"),
    (3674, "SEMICONDUCTORS & RELATED DEVICES"),
    (3677, "ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS"),
    (3678, "ELECTRONIC CONNECTORS"),
    (3679, "ELECTRONIC COMPONENTS, NEC"),
    (3690, "MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES"),
    (3695, "MAGNETIC & OPTICAL RECORDING MEDIA"),
    (3711, "MOTOR VEHICLES & PASSENGER CAR BODIES"),
    (3713, "TRUCK & BUS BODIES"),
    (3714, "MOTOR VEHICLE PARTS & ACCESSORIES"),
    (3715, "TRUCK TRAILERS"),
    (3716, "MOTOR HOMES"),
    (3720, "AIRCRAFT & PARTS"),
    (3721, "AIRCRAFT"),
    (3724, "AIRCRAFT ENGINES & ENGINE PARTS"),
    (3728, "AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC"),
    (3730, "SHIP & BOAT BUILDING & REPAIRING"),
    (3743, "RAILROAD EQUIPMENT"),
    (3751, "MOTORCYCLES, BICYCLES & PARTS"),
    (3760, "GUIDED MISSILES & SPACE VEHICLES & PARTS"),
    (3790, "MISCELLANEOUS TRANSPORTATION EQUIPMENT"),
    (3812, "SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS"),
    (3821, "LABORATORY APPARATUS & FURNITURE"),
    (3822, "AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS"),
    (3823, "INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL"),
    (3824, "TOTALIZING FLUID METERS & COUNTING DEVICES"),
    (3825, "INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS"),
    (3826, "LABORATORY ANALYTICAL INSTRUMENTS"),
    (3827, "OPTICAL INSTRUMENTS & LENSES"),
    (3829, "MEASURING & CONTROLLING DEVICES, NEC"),
    (3841, "SURGICAL & MEDICAL INSTRUMENTS & APPARATUS"),
    (3842, "ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES"),
    (3843, "DENTAL EQUIPMENT & SUPPLIES"),
    (3844, "X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS"),
    (3845, "ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS"),
    (3851, "OPHTHALMIC GOODS"),
    (3861, "PHOTOGRAPHIC EQUIPMENT & SUPPLIES"),
    (3873, "WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS"),
    (3910, "JEWELRY, SILVERWARE & PLATED WARE"),
    (3911, "JEWELRY, PRECIOUS METAL"),
    (3931, "MUSICAL INSTRUMENTS"),
    (3942, "DOLLS & STUFFED TOYS"),
    (3944, "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)"),
    (3949, "SPORTING & ATHLETIC GOODS, NEC"),
    (3950, "PENS, PENCILS & OTHER ARTISTS' MATERIALS"),
    (3960, "COSTUME JEWELRY & NOVELTIES"),
    (3990, "MISCELLANEOUS MANUFACTURING INDUSTRIES"),
    (4011, "RAILROADS, LINE-HAUL OPERATING"),
    (4013, "RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS"),
    (4100, "LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS"),
    (4210, "TRUCKING & COURIER SERVICES (NO AIR)"),
    (4213, "TRUCKING (NO LOCAL)"),
    (4220, "PUBLIC WAREHOUSING & STORAGE"),
    (4231, "TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT"),
    (4400, "WATER TRANSPORTATION"),
    (4412, "DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT"),
    (4512, "AIR TRANSPORTATION, SCHEDULED"),
    (4513, "AIR COURIER SERVICES"),
    (4522, "AIR TRANSPORTATION, NONSCHEDULED"),
    (4581, "AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES"),
    (4610, "PIPE LINES (NO NATURAL GAS)"),
    (4700, "TRANSPORTATION SERVICES"),
    (4731, "ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO"),
    (4812, "RADIOTELEPHONE COMMUNICATIONS"),
    (4813, "TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)"),
    (4822, "TELEGRAPH & OTHER MESSAGE COMMUNICATIONS"),
    (4832, "RADIO BROADCASTING STATIONS"),
    (4833, "TELEVISION BROADCASTING STATIONS"),
    (4841, "CABLE & OTHER PAY TELEVISION SERVICES"),
    (4899, "COMMUNICATIONS SERVICES, NEC"),
    (4900, "ELECTRIC, GAS & SANITARY SERVICES"),
    (4911, "ELECTRIC SERVICES"),
    (4922, "NATURAL GAS TRANSMISSION"),
    (4923, "NATURAL GAS TRANSMISISON & DISTRIBUTION"),
    (4924, "NATURAL GAS DISTRIBUTION"),
    (4931, "ELECTRIC & OTHER SERVICES COMBINED"),
    (4932, "GAS & OTHER SERVICES COMBINED"),
    (4941, "WATER SUPPLY"),
    (4950, "SANITARY SERVICES"),
    (4953, "REFUSE SYSTEMS"),
    (4955, "HAZARDOUS WASTE MANAGEMENT"),
    (4961, "STEAM & AIR-CONDITIONING SUPPLY"),
    (4991, "COGENERATION SERVICES & SMALL POWER PRODUCERS"),
    (5000, "WHOLESALE-DURABLE GOODS"),
    (5010, "WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES"),
    (5013, "WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS"),
    (5020, "WHOLESALE-FURNITURE & HOME FURNISHINGS"),
    (5030, "WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS"),
    (5031, "WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS"),
    (5040, "WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES"),
    (5045, "WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE"),
    (5047, "WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES"),
    (5050, "WHOLESALE-METALS & MINERALS (NO PETROLEUM)"),
    (5051, "WHOLESALE-METALS SERVICE CENTERS & OFFICES"),
    (5063, "WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES"),
    (5064, "WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS"),
    (5065, "WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC"),
    (5070, "WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES"),
    (5072, "WHOLESALE-HARDWARE"),
    (5080, "WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES"),
    (5082, "WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP"),
    (5084, "WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT"),
    (5090, "WHOLESALE-MISC DURABLE GOODS"),
    (5094, "WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS"),
    (5099, "WHOLESALE-DURABLE GOODS, NEC"),
    (5110, "WHOLESALE-PAPER & PAPER PRODUCTS"),
    (5122, "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES"),
    (5130, "WHOLESALE-APPAREL, PIECE GOODS & NOTIONS"),
    (5140, "WHOLESALE-GROCERIES & RELATED PRODUCTS"),
    (5141, "WHOLESALE-GROCERIES, GENERAL LINE"),
    (5150, "WHOLESALE-FARM PRODUCT RAW MATERIALS"),
    (5160, "WHOLESALE-CHEMICALS & ALLIED PRODUCTS"),
    (5171, "WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS"),
    (5172, "WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)"),
    (5180, "WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES"),
    (5190, "WHOLESALE-MISCELLANEOUS NONDURABLE GOODS"),
    (5200, "RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY"),
    (5211, "RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS"),
    (5271, "RETAIL-MOBILE HOME DEALERS"),
    (5311, "RETAIL-DEPARTMENT STORES"),
    (5331, "RETAIL-VARIETY STORES"),
    (5399, "RETAIL-MISC GENERAL MERCHANDISE STORES"),
    (5400, "RETAIL-FOOD STORES"),
    (5411, "RETAIL-GROCERY STORES"),
    (5412, "RETAIL-CONVENIENCE STORES"),
    (5500, "RETAIL-AUTO DEALERS & GASOLINE STATIONS"),
    (5531, "RETAIL-AUTO & HOME SUPPLY STORES"),
    (5600, "RETAIL-APPAREL & ACCESSORY STORES"),
    (5621, "RETAIL-WOMEN'S CLOTHING STORES"),
    (5651, "RETAIL-FAMILY CLOTHING STORES"),
    (5661, "RETAIL-SHOE STORES"),
    (5700, "RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES"),
    (5712, "RETAIL-FURNITURE STORES"),
    (5731, "RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES"),
    (5734, "RETAIL-COMPUTER & COMPUTER SOFTWARE STORES"),
    (5735, "RETAIL-RECORD & PRERECORDED TAPE STORES"),
    (5810, "RETAIL-EATING & DRINKING PLACES"),
    (5812, "RETAIL-EATING PLACES"),
    (5900, "RETAIL-MISCELLANEOUS RETAIL"),
    (5912, "RETAIL-DRUG STORES AND PROPRIETARY STORES"),
    (5940, "RETAIL-MISCELLANEOUS SHOPPING GOODS STORES"),
    (5944, "RETAIL-JEWELRY STORES"),
    (5945, "RETAIL-HOBBY, TOY & GAME SHOPS"),
    (5960, "RETAIL-NONSTORE RETAILERS"),
    (5961, "RETAIL-CATALOG & MAIL-ORDER HOUSES"),
    (5990, "RETAIL-RETAIL STORES, NEC"),
    (6021, "NATIONAL COMMERCIAL BANKS"),
    (6022, "STATE COMMERCIAL BANKS"),
    (6029, "COMMERCIAL BANKS, NEC"),
    (6035, "SAVINGS INSTITUTION, FEDERALLY CHARTERED"),
    (6036, "SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED"),
    (6099, "FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC"),
    (6111, "FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES"),
    (6141, "PERSONAL CREDIT INSTITUTIONS"),
    (6153, "SHORT-TERM BUSINESS CREDIT INSTITUTIONS"),
    (6159, "MISCELLANEOUS BUSINESS CREDIT INSTITUTION"),
    (6162, "MORTGAGE BANKERS & LOAN CORRESPONDENTS"),
    (6163, "LOAN BROKERS"),
    (6172, "FINANCE LESSORS"),
    (6189, "ASSET-BACKED SECURITIES"),
    (6199, "FINANCE SERVICES"),
    (6200, "SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES"),
    (6211, "SECURITY BROKERS, DEALERS & FLOTATION COMPANIES"),
    (6221, "COMMODITY CONTRACTS BROKERS & DEALERS"),
    (6282, "INVESTMENT ADVICE"),
    (6311, "LIFE INSURANCE"),
    (6321, "ACCIDENT & HEALTH INSURANCE"),
    (6324, "HOSPITAL & MEDICAL SERVICE PLANS"),
    (6331, "FIRE, MARINE & CASUALTY INSURANCE"),
    (6351, "SURETY INSURANCE"),
    (6361, "TITLE INSURANCE"),
    (6399, "INSURANCE CARRIERS, NEC"),
    (6411, "INSURANCE AGENTS, BROKERS & SERVICE"),
    (6500, "REAL ESTATE"),
    (6510, "REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS"),
    (6512, "OPERATORS OF NONRESIDENTIAL BUILDINGS"),
    (6513, "OPERATORS OF APARTMENT BUILDINGS"),
    (6519, "LESSORS OF REAL PROPERTY, NEC"),
    (6531, "REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)"),
    (6532, "REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)"),
    (6552, "LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)"),
    (6770, "BLANK CHECKS"),
    (6792, "OIL ROYALTY TRADERS"),
    (6794, "PATENT OWNERS & LESSORS"),
    (6795, "MINERAL ROYALTY TRADERS"),
    (6798, "REAL ESTATE INVESTMENT TRUSTS"),
    (6799, "INVESTORS, NEC"),
    (7000, "HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES"),
    (7011, "HOTELS & MOTELS"),
    (7200, "SERVICES-PERSONAL SERVICES"),
    (7310, "SERVICES-ADVERTISING"),
    (7311, "SERVICES-ADVERTISING AGENCIES"),
    (7320, "SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES"),
    (7330, "SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY"),
    (7331, "SERVICES-DIRECT MAIL ADVERTISING SERVICES"),
    (7340, "SERVICES-TO DWELLINGS & OTHER BUILDINGS"),
    (7350, "SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING"),
    (7359, "SERVICES-EQUIPMENT RENTAL & LEASING, NEC"),
    (7361, "SERVICES-EMPLOYMENT AGENCIES"),
    (7363, "SERVICES-HELP SUPPLY SERVICES"),
    (7370, "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC."),
    (7371, "SERVICES-COMPUTER PROGRAMMING SERVICES"),
    (7372, "SERVICES-PREPACKAGED SOFTWARE"),
    (7373, "SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN"),
    (7374, "SERVICES-COMPUTER PROCESSING & DATA PREPARATION"),
    (7377, "SERVICES-COMPUTER RENTAL & LEASING"),
    (7380, "SERVICES-MISCELLANEOUS BUSINESS SERVICES"),
    (7381, "SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES"),
    (7384, "SERVICES-PHOTOFINISHING LABORATORIES"),
    (7385, "SERVICES-TELEPHONE INTERCONNECT SYSTEMS"),
    (7389, "SERVICES-BUSINESS SERVICES, NEC"),
    (7500, "SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING"),
    (7510, "SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)"),
    (7600, "SERVICES-MISCELLANEOUS REPAIR SERVICES"),
    (7812, "SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION"),
    (7819, "SERVICES-ALLIED TO MOTION PICTURE PRODUCTION"),
    (7822, "SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION"),
    (7829, "SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION"),
    (7830, "SERVICES-MOTION PICTURE THEATERS"),
    (7841, "SERVICES-VIDEO TAPE RENTAL"),
    (7900, "SERVICES-AMUSEMENT & RECREATION SERVICES"),
    (7948, "SERVICES-RACING, INCLUDING TRACK OPERATION"),
    (7990, "SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION"),
    (7997, "SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS"),
    (8000, "SERVICES-HEALTH SERVICES"),
    (8011, "SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE"),
    (8050, "SERVICES-NURSING & PERSONAL CARE FACILITIES"),
    (8051, "SERVICES-SKILLED NURSING CARE FACILITIES"),
    (8060, "SERVICES-HOSPITALS"),
    (8062, "SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC"),
    (8071, "SERVICES-MEDICAL LABORATORIES"),
    (8082, "SERVICES-HOME HEALTH CARE SERVICES"),
    (8090, "SERVICES-MISC HEALTH & ALLIED SERVICES, NEC"),
    (8093, "SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC"),
    (8111, "SERVICES-LEGAL SERVICES"),
    (8200, "SERVICES-EDUCATIONAL SERVICES"),
    (8300, "SERVICES-SOCIAL SERVICES"),
    (8351, "SERVICES-CHILD DAY CARE SERVICES"),
    (8600, "SERVICES-MEMBERSHIP ORGANIZATIONS"),
    (8700, "SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT"),
    (8711, "SERVICES-ENGINEERING SERVICES"),
    (8731, "SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH"),
    (8734, "SERVICES-TESTING LABORATORIES"),
    (8741, "SERVICES-MANAGEMENT SERVICES"),
    (8742, "SERVICES-MANAGEMENT CONSULTING SERVICES"),
    (8744, "SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES"),
    (8880, "AMERICAN DEPOSITARY RECEIPTS"),
    (8888, "FOREIGN GOVERNMENTS"),
    (8900, "SERVICES-SERVICES, NEC"),
    (9721, "INTERNATIONAL AFFAIRS"),
    (9995, "NON-OPERATING ESTABLISHMENTS"),
)

SIC_TO_GICS_SECTOR: Mapping[int, str] = {
    100: "Consumer Staples",
    200: "Consumer Staples",
    700: "Consumer Staples",
    800: "Materials",
    900: "Consumer Staples",
    1000: "Materials",
    1040: "Materials",
    1090: "Materials",
    1220: "Energy",
    1221: "Energy",
    1311: "Energy",
    1381: "Energy",
    1382: "Energy",
    1389: "Energy",
    1400: "Materials",
    1520: "Industrials",
    1531: "Industrials",
    1540: "Industrials",
    1600: "Industrials",
    1623: "Industrials",
    1700: "Industrials",
    1731: "Industrials",
    2000: "Consumer Staples",
    2011: "Consumer Staples",
    2013: "Consumer Staples",
    2015: "Consumer Staples",
    2020: "Consumer Staples",
    2024: "Consumer Staples",
    2030: "Consumer Staples",
    2033: "Consumer Staples",
    2040: "Consumer Staples",
    2050: "Consumer Staples",
    2052: "Consumer Staples",
    2060: "Consumer Staples",
    2070: "Consumer Staples",
    2080: "Consumer Staples",
    2082: "Consumer Staples",
    2086: "Consumer Staples",
    2090: "Consumer Staples",
    2092: "Consumer Staples",
    2100: "Consumer Staples",
    2111: "Consumer Staples",
    2200: "Consumer Discretionary",
    2211: "Consumer Discretionary",
    2221: "Consumer Discretionary",
    2250: "Consumer Discretionary",
    2253: "Consumer Discretionary",
    2273: "Consumer Discretionary",
    2300: "Consumer Discretionary",
    2320: "Consumer Discretionary",
    2330: "Consumer Discretionary",
    2340: "Consumer Discretionary",
    2390: "Consumer Discretionary",
    2400: "Materials",
    2421: "Materials",
    2430: "Materials",
    2451: "Materials",
    2452: "Materials",
    2510: "Consumer Discretionary",
    2511: "Consumer Discretionary",
    2520: "Consumer Discretionary",
    2522: "Consumer Discretionary",
    2531: "Consumer Discretionary",
    2540: "Consumer Discretionary",
    2590: "Consumer Discretionary",
    2600: "Materials",
    2611: "Materials",
    2621: "Materials",
    2631: "Materials",
    2650: "Materials",
    2670: "Materials",
    2673: "Materials",
    2711: "Communication Services",
    2721: "Communication Services",
    2731: "Communication Services",
    2732: "Industrials",
    2741: "Communication Services",
    2750: "Industrials",
    2761: "Industrials",
    2771: "Consumer Discretionary",
    2780: "Industrials",
    2790: "Industrials",
    2800: "Materials",
    2810: "Materials",
    2820: "Materials",
    2821: "Materials",
    2833: "Health Care",
    2834: "Health Care",
    2835: "Health Care",
    2836: "Health Care",
    2840: "Consumer Staples",
    2842: "Consumer Staples",
    2844: "Consumer Staples",
    2851: "Materials",
    2860: "Materials",
    2870: "Materials",
    2890: "Materials",
    2891: "Materials",
    2911: "Energy",
    2950: "Materials",
    2990: "Energy",
    3011: "Consumer Discretionary",
    3021: "Consumer Discretionary",
    3050: "Materials",
    3060: "Materials",
    3080: "Materials",
    3081: "Materials",
    3086: "Materials",
    3089: "Materials",
    3100: "Consumer Discretionary",
    3140: "Consumer Discretionary",
    3211: "Materials",
    3220: "Materials",
    3221: "Materials",
    3231: "Materials",
    3241: "Materials",
    3250: "Materials",
    3260: "Materials",
    3270: "Materials",
    3272: "Materials",
    3281: "Materials",
    3290: "Materials",
    3310: "Materials",
    3312: "Materials",
    3317: "Materials",
    3320: "Materials",
    3330: "Materials",
    3334: "Materials",
    3341: "Materials",
    3350: "Materials",
    3357: "Materials",
    3360: "Materials",
    3390: "Materials",
    3411: "Materials",
    3412: "Materials",
    3420: "Industrials",
    3430: "Industrials",
    3433: "Industrials",
    3440: "Industrials",
    3442: "Industrials",
    3443: "Industrials",
    3444: "Industrials",
    3448: "Industrials",
    3451: "Industrials",
    3452: "Industrials",
    3460: "Industrials",
    3470: "Industrials",
    3480: "Industrials",
    3490: "Industrials",
    3510: "Industrials",
    3523: "Industrials",
    3524: "Industrials",
    3530: "Industrials",
    3531: "Industrials",
    3532: "Industrials",
    3533: "Industrials",
    3537: "Industrials",
    3540: "Industrials",
    3541: "Industrials",
    3550: "Industrials",
    3555: "Industrials",
    3559: "Industrials",
    3560: "Industrials",
    3561: "Industrials",
    3562: "Industrials",
    3564: "Industrials",
    3567: "Industrials",
    3569: "Industrials",
    3570: "Information Technology",
    3571: "Information Technology",
    3572: "Information Technology",
    3575: "Information Technology",
    3576: "Information Technology",
    3577: "Information Technology",
    3578: "Information Technology",
    3579: "Information Technology",
    3580: "Industrials",
    3585: "Industrials",
    3590: "Industrials",
    3600: "Industrials",
    3612: "Industrials",
    3613: "Industrials",
    3620: "Industrials",
    3621: "Industrials",
    3630: "Consumer Discretionary",
    3634: "Consumer Discretionary",
    3640: "Industrials",
    3651: "Consumer Discretionary",
    3652: "Communication Services",
    3661: "Information Technology",
    3663: "Information Technology",
    3669: "Information Technology",
    3670: "Information Technology",
    3672: "Information Technology",
    3674: "Information Technology",
    3677: "Information Technology",
    3678: "Information Technology",
    3679: "Information Technology",
    3690: "Industrials",
    3695: "Information Technology",
    3711: "Consumer Discretionary",
    3713: "Industrials",
    3714: "Consumer Discretionary",
    3715: "Industrials",
    3716: "Consumer Discretionary",
    3720: "Industrials",
    3721: "Industrials",
    3724: "Industrials",
    3728: "Industrials",
    3730: "Industrials",
    3743: "Industrials",
    3751: "Consumer Discretionary",
    3760: "Industrials",
    3790: "Industrials",
    3812: "Industrials",
    3821: "Health Care",
    3822: "Industrials",
    3823: "Industrials",
    3824: "Industrials",
    3825: "Industrials",
    3826: "Health Care",
    3827: "Industrials",
    3829: "Industrials",
    3841: "Health Care",
    3842: "Health Care",
    3843: "Health Care",
    3844: "Health Care",
    3845: "Health Care",
    3851: "Health Care",
    3861: "Consumer Discretionary",
    3873: "Consumer Discretionary",
    3910: "Consumer Discretionary",
    3911: "Consumer Discretionary",
    3931: "Consumer Discretionary",
    3942: "Consumer Discretionary",
    3944: "Consumer Discretionary",
    3949: "Consumer Discretionary",
    3950: "Consumer Discretionary",
    3960: "Consumer Discretionary",
    3990: "Unknown",
    4011: "Industrials",
    4013: "Industrials",
    4100: "Industrials",
    4210: "Industrials",
    4213: "Industrials",
    4220: "Industrials",
    4231: "Industrials",
    4400: "Industrials",
    4412: "Industrials",
    4512: "Industrials",
    4513: "Industrials",
    4522: "Industrials",
    4581: "Industrials",
    4610: "Energy",
    4700: "Industrials",
    4731: "Industrials",
    4812: "Communication Services",
    4813: "Communication Services",
    4822: "Communication Services",
    4832: "Communication Services",
    4833: "Communication Services",
    4841: "Communication Services",
    4899: "Communication Services",
    4900: "Utilities",
    4911: "Utilities",
    4922: "Utilities",
    4923: "Utilities",
    4924: "Utilities",
    4931: "Utilities",
    4932: "Utilities",
    4941: "Utilities",
    4950: "Industrials",
    4953: "Industrials",
    4955: "Industrials",
    4961: "Utilities",
    4991: "Utilities",
    5000: "Industrials",
    5010: "Consumer Discretionary",
    5013: "Consumer Discretionary",
    5020: "Consumer Discretionary",
    5030: "Industrials",
    5031: "Industrials",
    5040: "Industrials",
    5045: "Information Technology",
    5047: "Health Care",
    5050: "Industrials",
    5051: "Industrials",
    5063: "Information Technology",
    5064: "Information Technology",
    5065: "Information Technology",
    5070: "Industrials",
    5072: "Industrials",
    5080: "Industrials",
    5082: "Industrials",
    5084: "Industrials",
    5090: "Industrials",
    5094: "Industrials",
    5099: "Industrials",
    5110: "Industrials",
    5122: "Health Care",
    5130: "Consumer Discretionary",
    5140: "Consumer Staples",
    5141: "Consumer Staples",
    5150: "Consumer Staples",
    5160: "Materials",
    5171: "Energy",
    5172: "Energy",
    5180: "Consumer Staples",
    5190: "Consumer Staples",
    5200: "Consumer Discretionary",
    5211: "Consumer Discretionary",
    5271: "Consumer Discretionary",
    5311: "Consumer Discretionary",
    5331: "Consumer Discretionary",
    5399: "Consumer Discretionary",
    5400: "Consumer Staples",
    5411: "Consumer Staples",
    5412: "Consumer Staples",
    5500: "Consumer Discretionary",
    5531: "Consumer Discretionary",
    5600: "Consumer Discretionary",
    5621: "Consumer Discretionary",
    5651: "Consumer Discretionary",
    5661: "Consumer Discretionary",
    5700: "Consumer Discretionary",
    5712: "Consumer Discretionary",
    5731: "Consumer Discretionary",
    5734: "Consumer Discretionary",
    5735: "Consumer Discretionary",
    5810: "Consumer Discretionary",
    5812: "Consumer Discretionary",
    5900: "Consumer Staples",
    5912: "Consumer Staples",
    5940: "Consumer Discretionary",
    5944: "Consumer Discretionary",
    5945: "Consumer Discretionary",
    5960: "Consumer Discretionary",
    5961: "Consumer Discretionary",
    5990: "Consumer Discretionary",
    6021: "Financials",
    6022: "Financials",
    6029: "Financials",
    6035: "Financials",
    6036: "Financials",
    6099: "Financials",
    6111: "Financials",
    6141: "Financials",
    6153: "Financials",
    6159: "Financials",
    6162: "Financials",
    6163: "Financials",
    6172: "Financials",
    6189: "Financials",
    6199: "Financials",
    6200: "Financials",
    6211: "Financials",
    6221: "Financials",
    6282: "Financials",
    6311: "Financials",
    6321: "Financials",
    6324: "Financials",
    6331: "Financials",
    6351: "Financials",
    6361: "Financials",
    6399: "Financials",
    6411: "Financials",
    6500: "Real Estate",
    6510: "Real Estate",
    6512: "Real Estate",
    6513: "Real Estate",
    6519: "Real Estate",
    6531: "Real Estate",
    6532: "Real Estate",
    6552: "Real Estate",
    6770: "Unknown",
    6792: "Energy",
    6794: "Unknown",
    6795: "Materials",
    6798: "Real Estate",
    6799: "Financials",
    7000: "Consumer Discretionary",
    7011: "Consumer Discretionary",
    7200: "Consumer Discretionary",
    7310: "Communication Services",
    7311: "Communication Services",
    7320: "Industrials",
    7330: "Industrials",
    7331: "Industrials",
    7340: "Industrials",
    7350: "Industrials",
    7359: "Industrials",
    7361: "Industrials",
    7363: "Industrials",
    7370: "Information Technology",
    7371: "Information Technology",
    7372: "Information Technology",
    7373: "Information Technology",
    7374: "Information Technology",
    7377: "Information Technology",
    7380: "Industrials",
    7381: "Industrials",
    7384: "Consumer Discretionary",
    7385: "Information Technology",
    7389: "Industrials",
    7500: "Consumer Discretionary",
    7510: "Consumer Discretionary",
    7600: "Industrials",
    7812: "Communication Services",
    7819: "Communication Services",
    7822: "Communication Services",
    7829: "Communication Services",
    7830: "Communication Services",
    7841: "Communication Services",
    7900: "Consumer Discretionary",
    7948: "Consumer Discretionary",
    7990: "Consumer Discretionary",
    7997: "Consumer Discretionary",
    8000: "Health Care",
    8011: "Health Care",
    8050: "Health Care",
    8051: "Health Care",
    8060: "Health Care",
    8062: "Health Care",
    8071: "Health Care",
    8082: "Health Care",
    8090: "Health Care",
    8093: "Health Care",
    8111: "Industrials",
    8200: "Consumer Discretionary",
    8300: "Consumer Discretionary",
    8351: "Consumer Discretionary",
    8600: "Unknown",
    8700: "Industrials",
    8711: "Industrials",
    8731: "Health Care",
    8734: "Industrials",
    8741: "Industrials",
    8742: "Industrials",
    8744: "Industrials",
    8880: "Unknown",
    8888: "Unknown",
    8900: "Unknown",
    9721: "Unknown",
    9995: "Unknown",
}

_VALID_SIC_CODES = frozenset(code for code, _ in SEC_SIC_CODES)


def sic_to_gics_sector(sic_code: int) -> str | None:
    """Look up ``sic_code``'s GICS sector.

    Returns ``"Unknown"`` for a real SEC SIC code this crosswalk
    deliberately did not classify into one of the 11 GICS sectors (see
    module docstring) -- distinct from ``None``, returned when
    ``sic_code`` is not a real SEC SIC code at all (not present in
    ``SEC_SIC_CODES``). Callers should treat ``None`` as a data-quality
    signal (an unrecognized code was acquired) and ``"Unknown"`` as an
    expected, disclosed classification gap.
    """
    if sic_code not in _VALID_SIC_CODES:
        return None
    return SIC_TO_GICS_SECTOR.get(sic_code, "Unknown")
