"""Writes FilingMomentumReport artifacts (JSON, HTML) to disk, atomically.

``DEFAULT_REPORT_OUTPUT_ROOT`` is the AtlasQuant-local production report
root — never written to by the test suite (protected by
``tests/_safety.py``'s ``PROTECTED_PATH_NAMES``). Every test uses a
pytest ``tmp_path`` instead. No production report is generated by this
stage.
"""

from __future__ import annotations

import json
from pathlib import Path

from atlas_quant.reporting.serialization import write_json_atomic, write_text_atomic
from atlas_quant.strategies.filing_momentum_ml.reporting.html_template import render_report_html
from atlas_quant.strategies.filing_momentum_ml.reporting.report_model import FilingMomentumReport
from atlas_quant.strategies.filing_momentum_ml.reporting.serialization import report_to_dict

#: Production default report output root, one level below the repo root
#: (never inside ``src/``). Protected by tests/_safety.py.
DEFAULT_REPORT_OUTPUT_ROOT = Path(__file__).resolve().parents[5] / "outputs" / "reports"


def write_report_artifacts(
    report: FilingMomentumReport,
    root: Path,
    *,
    formats: tuple[str, ...] = ("json", "html"),
    overwrite: bool = True,
) -> dict[str, Path]:
    """Write ``report`` to ``root`` in each requested format, atomically.

    Returns a mapping of format -> written path. Never writes to
    :data:`DEFAULT_REPORT_OUTPUT_ROOT` from a test — that path is guarded.
    """
    root = Path(root)
    written: dict[str, Path] = {}
    identity = report.metadata.report_identity

    if "json" in formats:
        data = report_to_dict(report)
        # Deterministic JSON: json.dumps with sort_keys handles ordering;
        # write_json_atomic re-serializes to guarantee this even if `data`
        # came from an already-JSON-shaped dict.
        json.dumps(data)  # fail fast here if something is not serializable
        written["json"] = write_json_atomic(root / f"{identity}.json", data, overwrite=overwrite)

    if "html" in formats:
        html = render_report_html(report)
        written["html"] = write_text_atomic(root / f"{identity}.html", html, overwrite=overwrite)

    return written
